radicalbit/NSDb

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/actor/NamespaceSchemaActorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorBehaviour.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorShardSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorShardSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/ShardActorSpec.scala

This PR introduces a new actor `ShardReader` which has the responsibility to handle the read flow (e.g. query and get commands execution).
So now there are two separated actors:
- `ShardAccumulatorActor` which continues to handle the write logic as same as before and furthermore, it refre the reader actor when a bulk of writes is committed
- `ShardReaderActor` which handle the read logic and receive refresh

[NSDB-1] Separation of concerns

---

nsdb-cluster/src/main/resources/cluster.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetadataActor.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/index/MetadataIndex.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/util/FileUtils.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataTest.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedCacheSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorClusterTest.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/actor/LocationActorTest.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorSpec.scala
nsdb-core/src/main/resources/application.conf
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/Index.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/CommandApi.scala

In this PR, metrics shard metadata are retrieved from metadata index also on startup.
This implies the introduction of a warm-up behavior in coordinator start-up waiting for MetadataLocations.

Metadata warm-up

---

build.sbt
docker-compose.yml
docs/CLI_doc.md
docs/QuickStart.md

Use `nsdb` instead of `nsdb-cluster` as package name.
Below a table who summarize the changes:
| Package type | Previous value | Current value |
|--------------|----------------|---------------|
| `Universal` | `nsdb-cluster-<VERSION>.zip` | `nsdb-<VERSION>.zip` |
| `Rpm` | `nsdb-custer-<VERSION>-1.noarch.rpm` | `nsdb-<VERSION>-1.noarch.rpm` |
| `Debian` | `nsdb-cluster_<VERSION>_all.deb` | `nsdb_<VERSION>_all.deb` |
| `Docker` | `tools.radicalbit.io/nsdb-cluster:<VERSION>` | `tools.radicalbit.io/nsdb:<VERSION>` |

Use "nsdb" instead of "nsdb-cluster" as package name

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorSpec.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/protocol/Bit.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WsResources.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/WebSocketSpec.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/PublishSubscribeClusterSpec.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/WriteCoordinatorClusterSpec.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/MiniClusterSpec.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/ws/SynchronizedBuffer.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/ws/WebSocketClient.scala

This PR is for making the previous single node publish-subscribe feature support cluster by basically extending the high level gossip protocol for data and commit logs actor also for publisher actors.
When a a write event comes into the system, it will be spreaded across all the publishers, hence, regardless of which node is subscribed to a specific query, every event received on any node will be properly published

Fix publish-subscribe 

---

nsdb-cluster/src/main/resources/cluster.conf
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
project/Dependencies.scala

In order to get the artifacts correctly generated under scala 2.11, it's been necessary to remove some scala 2.12 specific implementations and dependencies usage

[hotfix] scala 2.11 compilation

---

docker-compose.yml
docs/SQL_doc.md
docs/Websocket.md
nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/console/NsdbILoop.scala
nsdb-cluster/src/main/resources/cluster.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NsdbNodeEndpoint.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-core/src/main/java/org/apache/lucene/facet/taxonomy/TaxonomyFacetSumDoubleAssociations.java
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WebResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiTest.scala
nsdb-kafka-connect/README.md
nsdb-kafka-connect/docker-compose.yml
nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkTask.scala
nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkWriter.scala
nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/ParsedKcql.scala
nsdb-kafka-connect/src/test/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkWriterSpec.scala
nsdb-kafka-connect/src/test/scala/io/radicalbit/nsdb/connector/kafka/sink/ParsedKcqlSpec.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
version.sbt

This PR allows the kafka connect users to specify if a mapped dimension is a tag or not.
This has made possible by the `WITHTAGS` syntactic construct provided by the KCQL library.

Tags support in kafka connect

---

build.sbt
nsdb-cluster/src/main/resources/cluster.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDBAkkaCluster.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/CommitLogCoordinator.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/test/resources/application.conf
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricsActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardOperation.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/lucene/OrderedTaxonomyFacetCounts.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/test/resources/application.conf
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricPerformerActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/BrokenTimeSeriesIndex.scala
nsdb-it/src/test/resources/minicluster.conf
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NSDbMiniClusterDefinition.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NSDbMiniClusterNode.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
project/Commons.scala
project/Dependencies.scala

This PR introduces the retry mechanism in the persistence process that happens in the background.
Basically, if any error occurs during index and facets writes, the operation is enqueued to be retried.
Retry operations include compensations (which are idempotent) and the retry in itself.
After a configurable attempts, the node is marked as inconsistent and will be shut down

Introduce Retry mechanism in persistence 

---

.travis.yml
build.sbt
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/FakeMetadataCache.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorErrorsSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/commit_log/RollingCommitLogFileWriterSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/FacetIndexTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/TimeSeriesIndexTest.scala

This Pr Improves the design of the method that retrieves the NSDb coordinates.
- getDbs
- getNamespaces given a Db
- getMetrics given a Db and a Namespace
Basically, a dedicated distributed cache entry has been provided and used to retrieve the coordinates instead of relying on the children actors

Improve Coordinate Retrieval

---

docs/JVM_API_doc.md
nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/console/NsdbILoop.scala
nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/table/ASCIITableBuilder.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/index/MetricInfoIndex.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCache.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/index/MetricInfoIndexTest.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/model/MetricInfo.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/protocol/EndpointProtocol.scala
nsdb-java-api/src/main/java/NSDBInitMetric.java
nsdb-java-api/src/main/java/io/radicalbit/nsdb/api/java/DescribeMetricResult.java
nsdb-java-api/src/main/java/io/radicalbit/nsdb/api/java/MetricInfoResult.java
nsdb-java-api/src/main/java/io/radicalbit/nsdb/api/java/NSDB.java
nsdb-java-api/src/main/java/io/radicalbit/nsdb/api/java/SchemaField.java
nsdb-rpc/src/main/protobuf/init.proto
nsdb-rpc/src/main/protobuf/responseCommand.proto
nsdb-rpc/src/main/protobuf/service.proto
nsdb-rpc/src/main/scala/io/radicalbit/nsdb/client/rpc/GRPCClient.scala
nsdb-scala-api/src/main/scala/io/radicalbit/nsdb/api/scala/NSDB.scala
nsdb-scala-api/src/main/scala/io/radicalbit/nsdb/api/scala/NSDBDescribe.scala
nsdb-scala-api/src/main/scala/io/radicalbit/nsdb/api/scala/NSDBMetricInfo.scala
nsdb-scala-api/src/main/scala/io/radicalbit/nsdb/api/scala/example/NSDBMain.scala

This PR has the purpose to add `retention` as a possible configuration of a metric in the Init Metric API.
The retention must be set as an interval.
```
NSDB.BitInfo metricInfo = nsdb.db("root")
.namespace("registry")
.bit("people")
.shardInterval("2d")
.retention("2d");
```
Also, the info response (if present for the specified metric) has been added to the describe metric api.

Add Retention In Init JVM API

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinator.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/AbstractReadCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/RetentionSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorErrorsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteInterval.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/FakeCommitLogCoordinator.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCache.scala

This PR aims to extend the retention implementation by adding the management of the partially outdated locations.
When the locations check is performed, so far only the completely outdated ones are evicted.
With this PR, a delete statement is executed against all the partially outdated ones in order to delete the outdated records inside of them and keep the location itself.

[Retention] Delete records inside partially outdated locations

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/util/ErrorManagementUtils.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/util/FileUtils.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricsActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/CommitLogWriterActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AllFacetIndexes.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Location.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricPerformerActorSpec.scala

This PR's intent is to remove the outdated locations remained after the evition process.
So far, in fact, those locations are simply Unlinked from the metadata, thus, they are not considered during queries, but they are still written in the file system.
This PR is to remove those locations in 2 different moments:
- when the eviction is performed; plus unlink the location, it will be deleted from the FS
- a periodical check if there is some outdated location is performed.

[RETENTION ]Delete outdated phisical locations

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Location.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/TimeRange.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/TimeRangeManager.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/TimeRangeManagerSpec.scala

This PR improves the time range queries by calculating the time intervals globally, i.e. the upper boundary and the lower boundary are calculated by looking up to all the shards and not by demanding the calculation to each shard.
Each shard is only responsible to check if there are records for the global intervals.
By doing this, it will be avoided any possible overlap between the time intervals specified in the query and the metric partitions

Global Temporal Continuity

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSimpleStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinatorSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/SchemaIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/TypeSupport.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/lucene/Index.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Schema.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/SchemaIndexTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/TimeSeriesIndexTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/CommandApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/CommandApiTest.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiTest.scala

This PR has the purpose to implement 2 optimizations:
- a Map has been chosen as the data structure to store schema fields (in order to optimize read accesses)
- The reader and accumulator actors management has been separated in MetricDataActor

Schema Fields And Data children actors optimization

---

docs/SQL_doc.md
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/CommandStatementParser.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/CommandStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/DeleteSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/InsertSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala

This Pr adds support for round brackets in where conditions; with this feature, it's possible to set custom associativity of a chain of operators
e.g. 
```
SELECT dimension FROM metric WHERE string_dimension = myStringValue AND (another_string_dimension LIKE startWith$ OR a_further_dimension >= 0)
SELECT dimension FROM metric WHERE NOT (string_dimension = myStringValue AND another_string_dimension LIKE startWith$ OR a_further_dimension >= 0)
```
are now valid statements

Round brackets support

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/CommitLogFile.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/RollingCommitLogFileWriter.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/TimeRangeManagerSpec.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala

This PR will fix the following bugs
- if the calculated ranges for a temporal group by are null. The query fails
- There is a syntactical  ambiguity in SQL parser for temporal group by with a limit

[BUGFIX] fix temporal queries on empty intervals and for limit

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WsResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/CommandApiTest.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/WebSocketSpec.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/PublishSubscribeClusterSpec.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/ws/SynchronizedBuffer.scala

This PR aims to apply a few small optimizations to the streaming flow.
In particular:
* remove the unused subscribe by query id operation
* use a queue instead of a map for buffering events to publish (map's capabilities are no longer needed)
* avoid message transfer from WriteCoordinator to PublisherActor during replica write

Streaming Flow Optimized

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NsdbNodeEndpoint.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WsResources.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/WebSocketSpec.scala
nsdb-security/src/main/scala/io/radicalbit/nsdb/security/Security.scala

This PR allows receiving custom headers (e.g. for security purposes) in a WebSocket request passed as a subprotocols.
More information can be found [here](https://hpbn.co/websocket/#subprotocol-negotiation)
Even if this might be a non-pure and not clean solution, it is the more pragmatic and effective way to pass custom headers in a ws request (afaik the only valid mechanism)

Use Web-socket subprotocol for custom headers passing

---

nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WsResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/DataApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/validation/FieldErrorInfo.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/validation/ModelValidationRejection.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/validation/ValidationDirective.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/validation/Validator.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/validation/ValidatorRegexHelpers.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/validation/Validators.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/DataApiTest.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/validation/ValidatorsTest.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/RegexNSDb.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala

With this PR we deal with the problem of validating object fields received from data POST API.
This PR has been inspired from [here](http://fruzenshtein.com/akka-http-another-one-validation-directive/)
The main idea is to have a vaidation that could be as general as possible and do not make custom validation for each object.

Validate json object fields in data API

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/CommitLogCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSimpleStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializer.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/TimeRangeManager.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializerSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/TimeRangeManagerSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryEnrichmentTest.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/DeleteSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/RelativeTimeSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala

This pr is in preparation for the modification of the /query api that with one optional parameter can return the query structure in addition to the result of the query
- parsing "now +- {quantity}{unitMeasure}" in queries take track of the relative timestamp, with an object that has: absolute timestamp value, plus or minus sign, quantity (1, 2, 3, ...) and unit measure (s, m, h or d)
- parsing of group by with time interval take track of the quantity and unit measure (same as above without the sign because there isn't the sign in interval)
- add some tests for relative timestamp queries and fixed queries with group by time interval tests

Add fields to objects returned by SQLStatementParser

---

nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/CustomSerializers.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/CommandApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/DataApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryValidationApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiTest.scala

This PR completes #89 adding the possibility to have the parsed query (in json) returned from the /query API using an optional parameter in the POST request
- with optional boolean parsed parameter in the request we can have the parsed query returned, omitting the parameter the api will only return the data retrieved
- added some tests to test the new functionality, in particular for relative values tests there is an additional custom serializer that is plugged in that cut off the now timestamp (replacing it with a 0) in order to make the test time independent.
- CustomSerializers.scala can be eventually used to plug-in other custom serializers
PS: please focus on implicit formats changes to see if they are correct

Improve http api to return json of parsed query

---

k8s/nsdb-cluster.yml
k8s/nsdb-service.yml
nsdb-cluster/src/main/resources/application-k8s.conf
nsdb-cluster/src/main/resources/nsdb.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDBAkkaCluster.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NsdbClusterConfigProvider.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/util/ErrorManagementUtils.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCache.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/RollingCommitLogFileChecker.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/util/ConfigKeys.scala
nsdb-it/src/test/resources/application-k8s.conf
project/Dependencies.scala

This PR allows a cluster formation inside a k8s deployment (statefulset is not supported at the moment)
The implementation strongly leverages akka management library that can be found here:
https://doc.akka.io/docs/akka-management/current/bootstrap/kubernetes.html
inside the k8s folder, we can find a deployment and service example

K8s deployments support

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCache.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCoordinator.scala

This PRs, besides applying some optimization in the distributed cache and removing a useless key previously managed, adds the `delete locations by node` that will be bound to the cluster events in a following PR

Evict locations for a Node

---

nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/RelativeTimeSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala

This PR solves the following problem:
- `... WHERE timestamp < now`
nsdb sql parser didn't allow this before the bugfix

modify now clause allowing absolute comparison

---

nsdb-cluster/src/main/resources/kamon.conf
nsdb-cluster/src/main/resources/monitoring.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDbActors.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NsdbCluster.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/ProductionCluster.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/util/ConfigKeys.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NSDBAkkaMiniCluster.scala
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NSDbMiniClusterNode.scala
project/Dependencies.scala
project/plugins.sbt

This PR enable a monitoring system powered by kamon (https://kamon.io/)
It's configured to sink data to an embedded prometheus target
Inside `monitoring.conf` it's possible to enable the monitoring system

Add Monitoring powered by Kamon

---

.gitignore
.travis.yml
nsdb-cluster/src/main/resources/application-common.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/package.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/util/FileUtils.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerTestActor.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/CommandApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/DataApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryValidationApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/WebSocketSpec.scala
nsdb-it/src/test/resources/application-common.conf
nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala
project/Dependencies.scala
project/build.properties

This PR introduces NSDb metrics.
Basically, it leverages Akka cluster metrics and akka distributed publish-subscribe in order to collect inside the cluster listener actor, the usable space in percentage.
This metrics will be essential in order to determine the node to use for writing operations

Introduce NSDb Metrics

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/metrics/DiskMetricsCollector.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/metrics/DiskMetricsSelector.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/metrics/NSDbMetrics.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/package.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/metrics/DiskMetricsSelectorSpec.scala

This PR introduces the `DiskMetricsSelector` entity, which is responsible to collect all the metrics related to the disk utilization and to calculate a node capacity in terms of the disk.
If the capacity is 0.0, it means that all the disk has been used, 1.0 if all the disk is free

Add DiskMetricsSelector

---

nsdb-cluster/src/main/resources/nsdb.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDbActors.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/logic/CapacityWriteNodesSelectionLogic.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/logic/WriteNodesSelectionLogic.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/metrics/DiskMetricsSelector.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/metrics/NSDbMixMetricSelector.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerTestActor.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/RetentionSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCache.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/logic/CapacityWriteNodesSelectionLogicSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/metrics/DiskMetricsSelectorSpec.scala

This PR introduces a solid write node choice algorithm that is based on nodes capacity.
The user can configure which metric should be used to calculate the node capacity, i.e. the weight used to choose a set of nodes to write replicas in.
This implementation has been largely inspired by the Akka adaptive load balancing
https://doc.akka.io/docs/akka/current/cluster-metrics.html#adaptive-load-balancing
The metrics collected and the logic used above to route a message in a set of routees, here in NSDb is used to retrieve a set of nodes based on its capacity.
Allowed metrics are:
heap, load, cpu, disk, mix
All those metrics have already been implemented in the Akka project except for the disk one, which has been implemented ad hoc and measures the free disk ration (aka disk capacity).
This …

Write node choice Algorithm

---

build.sbt
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiSupport.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WebResources.scala
project/plugins.sbt

This PR adds a custom header to any http api response in order to communicate the current nsdb version to an http client

[HOTFIX] Add nsdb version as api response header

---

.travis.yml
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/util/FileUtils.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSimpleStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorValidateStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardOperation.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializer.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Location.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/TimeRangeManager.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializerSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/TimeRangeManagerSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/CustomSerializers.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryEnrichmentTest.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/DeleteSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala
project/Dependencies.scala

This PR aims to make the codebase more serialization friendly.
In particular, the following guidelines have been applied
- uniform (in favour of case classes) all the ADTs with a mixture of case classes and object as children.
- remove usage of tuples in favour of case classes
- upgrade Json and serialization related dependencies in order to avoid any possible clash

[HOTFIX] Serialization propaedeutic

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NsdbNodeEndpoint.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializer.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/TimeRangeManager.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WebResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiTest.scala

This PR aims to fix the inheritance of json formatter objects.
Now, the concrete definition is made on the last child.
Also, the serialization of the NotExression has been improved

[Hotfix] Uniform Json formatters inheritance

---

docs/RestApis.md
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/CustomSerializers.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/CustomSerializerForTest.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiTest.scala

This PR is a hotfix for PR #109 in to correctly align the parsed query http api with the new serialization mechanism.
Furthermore:
- bugfix because I forgot to add to the custom serializer list the NullableExpressionSerializer
- some tests that check not and null serializers
- moved the CustomSerializerForTesting to test folder because that serializer is only for test and so it shouldn't be in the same file of all custom serializers.
- add docs for parsed query http api (please check if it's correct and in the correct place)

[HOTFIX] fix for not and null serializers for tokenized query

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala

This PR Improves the coordinators unsubscription mechanism making it explicit the removal command in the `Unreacheable` callback of the `ClusterListener`

Improve Unsubscription

---

nsdb-cluster/src/main/resources/nsdb.conf
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedSchemaCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/logic/WriteConsistencyLogic.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedSchemaCacheSpec.scala
nsdb-it/src/main/resources/nsdb-minicluster.conf

In this PR we give the possibility to choose the write consistency of nsdb cluster: all or majority.
In few words, write all consistency means that when you request to write a Bit, the data will be replicated among all nodes, while majority write the data will be reploicated among n(nodes) / 2 +1

insert in conf write consistency: all or majority

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Schema.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParserErrors.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiTest.scala

This PR has the purpose to improve the error messages returned in case of an invalid statement provided.
Basically:
- Either has been used in favour of Try to handle errors
- Accessors methods are added in Schema object to access tags dimensions and value independently

Improve Parser Error Messages

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinator.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedSchemaCacheSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinatorSpec.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/protocol/Bit.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/TypeSupport.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Schema.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/TimeSeriesIndexTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/aux/FirstLastIndexSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/aux/MinMaxIndexSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/WebSocketSpec.scala

This PR aims at improving and making safer the Schema API.
In particular, the Schema primary constructor is going to become private so that Schema must be inferred from a Bit and not arbitrarily  created

[HOTFIX] Allow schema creation only from bit

---

nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/console/NsdbILoop.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/QueryEnriched.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryValidationApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/WebSocketSpec.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/CommandStatementParser.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/StatementParserResult.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/CommandStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/DeleteSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/InsertSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/RelativeTimeSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala

This PR aims at 
* creating an isolated object `QueryEnriched` which apply filters to a query.
This object can be reused in other parts of the codebase (e.g. in WebSockets)
* improving SQL and command parser result structures. 
The main benefit is to avoid usage of `Try` in favour of a dedicated adt

Improve Query Enrichment and Parser Result 

---

docs/Websocket.md
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/protocol/Bit.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/NSDbJson.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/NSDbJsonProtocol.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WebResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WsResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/DataApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryValidationApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/EmptyReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/DataApiTest.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryParserApiSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryValidationApiSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/RealTimeApiSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/RealTimeFiltersSpec.scala

This PR aims at adding real-time filters to the WebSockets APIs.
Basically, as per the documentation, it is possible to specify a time range ad an array of conditions that will be chained to the query where clause using the and operator
For example, It's possible to use the following json to subscribe to a query.
```
{
"db": "db",
"namespace": "namespace",
"metric": "people",
"queryString": "select * from people limit 100",
"from": 0,
"to": 100000,
"filters": [{ "dimension": "dimName1",
"value" : "value",
"operator": "=" },
{ "dimension": "dimName2",
"value" : 1,
"operator": "=" }
]
}
```
That json will be processed by the `QueryEnriched` class that will produce the following query:
`select * from people where timestamp > 0 AND timestamp < 100000 and timName1 = value and dimName2 = 1`

Add Real-Time Filters

---

nsdb-common/src/main/scala/io/radicalbit/nsdb/common/package.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializer.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/TimeRangeManager.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/CustomSerializers.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/CustomSerializerForTest.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/DeleteSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/RelativeTimeSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala

This PR has the purpose to _erase_ the generic type of the following objects
* `ComparisonExpression`
* `EqualityExpression`
* `RangeExpression`
Those objects depend now by the internal type system

Bound Sql Statements Results to the Internal Type System

---

nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLEqExpressionSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLLikeExpressionSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala

This PR has the purpose of:
* improving like expressions by adding the support of quotes and thus string with spaces
(e.g. `select * from metrics where field like 'string with space'`)
* improving like and equal expression by adding the support for the following special chars
`_`, `-`, `:`, `~`
(e.g. `select name from people where name = '_spe~cial:_- with. space'`)

Improve Special Characters Support

---

k8s/nsdb-cluster-stateful.yml
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala

This PR fixes the unsubscribe child actor process in case one node gracefully leaves the cluster.
In case a node is restarted or gracefully stopped (the leave event is propagated by the Akka cluster) we ensure that the unsubscribe process takes place.
In case a node becomes unreachable and then it is downed forcefully the unsubscribe process will take place twice, but, since that is an idempotent operation, we can afford this.

[HOTFIX] Fix unsubscribe child actors when downing

---

nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSimpleStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/TemporalReadCoordinatorSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/test/MiniClusterSpec.scala
nsdb-it/src/main/scala/io/radicalbit/nsdb/minicluster/MiniClusterStarter.scala
nsdb-it/src/main/scala/io/radicalbit/nsdb/minicluster/NSDbMiniClusterConfigProvider.scala
nsdb-it/src/main/scala/io/radicalbit/nsdb/minicluster/NSDbMiniClusterNode.scala
nsdb-it/src/main/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala

This PR allows avoiding non-efficient management of time ranges in case of a temporal query.
All the buckets that have a zero value (for all the possible aggregations) will be discarded.
Also, the integration tests have been improved. Now it's possible to easily set the shard interval for a single test class and also many integration tests for temporal queries have been added

[HOTFIX] Discard empty time buckets

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AllFacetIndexes.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/AllFacetIndexSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/FacetIndexTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/TimeRangeFacetTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala

This PR adds the average retrieval from indexes for temporal average queries.
Essentially, the sum and the count are simultaneously retrieved and the results are combined in a single Bit.
Purpose of the post-processing phase will be to reduce all the partial results and therefore calculate the actual average.
The post-processing phase will be implemented in a future PR

Temporal Average Index Retrieval

---

docs/RestApis.md
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/Filters.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/NSDbJson.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/QueryEnriched.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryApi.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryApiSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryEnrichmentSpec.scala

This PR enables a more idiomatic GET rest API for submitting a select query.
Since we are going to add the support for delete statements in rest API, it would be idiomatic to have a GET API for select queries and a POST for delete or update (that we will never support :) )  queries.
Anyway, the existing POST query API is kept for backward compatibility.
Any thought on that is really welcome and appreciated.

[HOTFIX] GET query api

---

nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/RealTimeProtocol.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/NSDbJson.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala

This PR reintroduce the query identifier in the `SubscribedByQueryString` message that is sent to a subscriber as the response for a subscription operation

[HOTFIX] Restore quid in Websocket protocol

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Schema.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/TimeContext.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserAggregationsSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserRelativeTimeSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/CustomSerializers.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/CustomSerializerForTest.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryParserApiSpec.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/RelativeTimeSQLStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SQLStatementBracketsSpec.scala

This PR introduces one new feature and consolidates an existing one
- a TimeContext has been introduced. 
By now, it will include the current time and the timezone. 
The object is centrally initialized inside coordinators and used to calculate relative time expression throughout all the shards.
- Duration labels are now compliant with the Java and Scala nomenclature:
allowed values are now 
```
d, day, 
h, hour
min minute
s, sec, second
```

Time context And Standard Durations

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/logic/ReadNodesSelection.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParserErrors.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/TimeRangeManager.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserAggregationsSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/TimeRangeManagerSpec.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/EmptyReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/actor/FakeReadCoordinator.scala
nsdb-http/src/test/scala/io/radicalbit/nsdb/web/QueryEnrichmentSpec.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/GracePeriodStatementSpec.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/RelativeTimeSQLStatementSpec.scala

This PR introduces the concept of grace period:
In the SQL parser the `since` clause has been enabled. It will be possible to specify it at the end of a SQL query in order to set the amount of time backwards that must consider.
e.g. `select count(*) from metric group by  interval 10s since 6h` will return all the time buckets from 6h ago  
The `since` clause is allowed only on temporal group by queries. It will be rejected otherwise

Grace Period for Temporal Queries

---

nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala

This PR adds the management of late events in real-time streaming.
The `since` clause in temporal queries is used to determine a grace period for pushing records that come in the past (late events). 
Every pushed time bucket will be store for the grace period and whenever a late event comes, it will be aggregated  with the related bucket ad pushed again.

Manage late events in temporal query streaming

---

nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorDistinctAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedData/MockedData.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/protocol/Bit.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SqlStatementSerialization.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/lucene/Index.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/aux/CountDistinctSpec.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/NSDbJson.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/ReadCoordinatorClusterSpec.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
project/Dependencies.scala

This PR enables the SQL clause "count distinct" that it's applicable only on the value (on * as syntactic sugar) and only on group by queries.
So for instance, It will be possible to perform queries like
`select count(distinct *) from metric group by tag where timestamp > 0`

Count Distinct for group by queries

---

nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorGlobalAggregatedStatementsSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/lucene/Index.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Schema.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParserErrors.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserAggregationsSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/GlobalAggregationReadCoordinatorSpec.scala

This PR enables the count distinct for global queries (i.e. queries without a group by clause).
For instance, now expressions like
```
select count(distinct *) from metric 
select count(distinct *) from metric where tag = "constant"
```
will be supported

Count Distinct for global queries

---

nsdb-rpc/src/main/scala/io/radicalbit/nsdb/client/rpc/GRPCServer.scala
project/Dependencies.scala

This PR enables `GRPC Server Reflection Protocol` that is an extension of a Grpc server that allows a client to list all the available service and call a specific method without having the protobuf descriptor

[HOTFIX] Enable grpc reflection

---

.travis.yml
build.sbt
project/Commons.scala
project/Dependencies.scala
project/plugins.sbt

This PR enables cross scala version (2.12 - 2.13) for scala APIs and all the dependant modules.
The other modules won't be affected by this modification.
Many dependencies are updated in order to support the newer scala version and the build has been updated in order to cross-publish the artifacts

Enable scala 2.13 in APIs

---

build.sbt
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorSimpleStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedData/MockedData.scala
nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLEqExpressionSpec.scala
project/Commons.scala
project/Dependencies.scala
project/assembly.sbt
project/protoc.sbt

This PR fixes the management of empty strings as comparison terms.
Now it's possible to insert empty string tags and also to provide an empty string as an equality comparison term. 
e.g. 
```sql
select * from metric where tag = ''
```

[HOTFIX] Fix support for empty strings

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalDistinctAggregatedStatementsSpec.scala
nsdb-core/src/main/java/org/apache/lucene/search/grouping/NSDbLongRangeFactory.java
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/model/TimeRange.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/aux/NSDbLongRangeFactoryTest.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/aux/UniqueRangeValuesSpec.scala
nsdb-it/README.md
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/TemporalReadCoordinatorSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/test/MiniClusterSpec.scala
nsdb-minicluster/src/main/scala/io/radicalbit/nsdb/minicluster/MiniClusterStarter.scala
nsdb-minicluster/src/main/scala/io/radicalbit/nsdb/minicluster/NSDbMiniCluster.scala
nsdb-minicluster/src/main/scala/io/radicalbit/nsdb/minicluster/test/MiniClusterSingleNodeSpec.scala
project/Dependencies.scala

This PR enables count distinct aggregation on temporal queries.
For instance, expressions like
```
select count(distinct *) from metric group by interval 60s
select count(distinct *) from metric group by interval 60s where tag = "constant" order by timestamp desc
```
will be supported

Count Distinct aggregation for temporal queries

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/AbstractClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/logic/WriteConfig.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCache.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCoordinator.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala

This PR aims at :
- making the location load process at the node startup faster by adding entries to the akka cache with the local consistency (synchronous ack from the local node only then asynchronous dissemination)
- fixing the realtime query unsubscribe process by properly closing the created scheduler task

Lightened location load at node startup

---

.travis.yml
nsdb-core/src/main/scala/io/radicalbit/nsdb/monitoring/NSDbMonitoring.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/WebResources.scala
nsdb-http/src/main/scala/io/radicalbit/nsdb/web/actor/StreamActor.scala
project/Dependencies.scala
project/plugins.sbt

This PR adds a custom kamon metric about the WebSocket opened connection.
It's a Kamon gauge that is incremented during the prestart of the StreamActor (that is 1:1 coupled with the HTTP WebSockets channels) and decremented during its poststop.

Add Websocket connections Monitoring metric

---

nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/TimeRangeFacetSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/TemporalReadCoordinatorSpec.scala

This PR aims at including empty temporal buckets in temporal queries response that were discarded in the previous implementation.
The exclusion of empty buckets was deliberated, therefore there is only a little change in the main code.
Of course, many tests must have been updated accordingly.

Include Empty buckets in temporal queries result

---

nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalDistinctAggregatedStatementsSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/util/FileUtils.scala

The time range calculation during the execution of a temporal query is shard based. It might happen that a shard ends in a future timestamp.
Aims of this PR is to exclude temporal buckets that are in the future.
The current tiemstamp  is given by the time-context, and  might be set manually or otherwise os set to the current system time

[HOTFIX] Exclude Future Buckets from temporal queries

---

.github/workflows/ci.yml
build.sbt
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/AbstractClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/extension/NSDbClusterSnapshot.scala
nsdb-cluster/src/multi-jvm/resources/application.conf
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerTestActor.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/ClusterSingletonWithSplitBrainSpec.scala
nsdb-cluster/src/test/resources/application.conf
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/RetentionSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorErrorsSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorSpec.scala
nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/MockedClusterListener.scala
nsdb-common/src/test/resources/nsdb-test.conf
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
nsdb-core/src/test/resources/application.conf
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/PublisherActorSpec.scala
project/Commons.scala

This PR aims at improving tests and CI in order to achieve more stability in the whole process.
The following criteria have been adopted:
- Cluster ActorrefProvider has been replaced by LocalActorrefProvider in tests. This has made possible by a little refactor of metadata coordinator in order to remove all the akka cluster references.
- many not useful `within` constraints have been removed.
- fix wrong usage of TestProbes 
- make the minimum usage of TestActorRef

Reinforce Test To Make CI More stable

---

nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/GlobalAggregationReadCoordinatorSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/PublishSubscribeGrpcClusterSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/ReadCoordinatorClusterSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/TemporalReadCoordinatorSpec.scala
nsdb-it/src/it/scala/io/radicalbit/nsdb/test/MiniClusterSpec.scala
nsdb-minicluster/src/main/scala/io/radicalbit/nsdb/minicluster/NSDbMiniCluster.scala

From a suggestion by @artur-rashitov, who noticed, that records in IT were inserted only on one node, a convenience method called `withRandomNodeConnection` is used for every write operation involving test data preparation. In this way we are sure that data is scattered among cluster nodes

Improve Integration test stability And Reliability

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDbActors.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/AbstractClusterListener.scala
nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/MetadataRestoreSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/NodeActorGuardianForTest.scala

This PR is for improving the top levl actor creation and hierarchy.
In particular, `ClusterListenerActor` has been transformed into a child of `DatabaseActorGuardian` which is a new top level actor. All the coordinator are its siblings.
Basically the new hierarchy might be summarized as follows:
* NodeActorGuardian
*  ClusterListener
* [*]Coordinator
* [*]DataActor
NodeActorGuardian will have (in future developments) the responsibility to provide a tailored supervision strategy to all the coordinators, data and listener actors.

Top Level Actors Hierarchy

---

nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
nsdb-cluster/src/multi-jvm/resources/application.conf
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/NodeActorGuardianForTest.scala
nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/SupervisionSpec.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricPerformerActor.scala
nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/supervision/OneForOneWithRetriesStrategy.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricPerformerActorSpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/supervision/OneForOneWithRetriesStrategySpec.scala
nsdb-core/src/test/scala/io/radicalbit/nsdb/index/BrokenTimeSeriesIndex.scala

This PR Introduces a new supervision strategy class 
`OneForOneWithRetriesStrategy.scala`
The idea behind this new strategy is that in case of a resume Directive,  the `maxNrOfRetries` approach can be applied as it is for the restart directive.
For many scenarios, NSDb actors must be supervised with the resume approach, in order to preserve actor's statuses.
After a configurable number of attempts, a fatal behaviour must be applied.
Inside `NodeActorGuardian` a custom supervision approach has been implemented.
Except for `InvalidLocationsInNode` that is a custom exception thrown my `MetricAccumulator` after a separated retry mechanism, only a Resume directive is applied, with a configurable retry attempts

Custom supervision strategy
