- nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkConnector.scala
- nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkTask.scala
- nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkWriter.scala
- nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/ParsedKcql.scala
- nsdb-kafka-connect/src/main/scala/io/radicalbit/nsdb/connector/kafka/sink/conf/Constants.scala
- nsdb-kafka-connect/src/test/scala/io/radicalbit/nsdb/connector/kafka/sink/NsdbSinkWriterSpec.scala
Along this I did the following:
- enriched logging
- collected constants
- added support for bigDecimal in values
- added type checking on not desired optional for value
- fixed some typos
- added more tests
> [#7] Enriching types support for Kafka Connector

- nsdb-cluster/src/main/resources/cluster.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/DatabaseActorsGuardian.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActor.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataTest.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorClusterTest.scala
- nsdb-cluster/src/test/resources/application.conf
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/actor/MetricsDataActorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardAccumulatorActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/Index.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
- nsdb-core/src/test/resources/application.conf
- nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/ShardActorSpec.scala
- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/Web.scala
This PR is for making `ShardReaderActor` a router in order to handle a bigger amount of concurrent read requests
> Increment Read Throughput By using Routers

- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/Web.scala
Fixed wrong conf `http-endpoint`
> Fixed wrong conf

- .gitignore
- build.sbt
- docker-compose.yml
This PR aims to:
- create a user and group to run NSDb into docker image (to prevent security issue)
- update and fix docker-compose file configuration
> Run NSDb with a dedicated user and group into Docker image

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataTest.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorClusterTest.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActorSpec.scala
This PR will break the compatibility with the previous shards structure.
Nowon shards boundaries are computed based on shard-interval.
> Introduce new sharding algorithm

- nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/console/NsdbILoop.scala
- nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/table/ASCIITableBuilder.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/protocol/EndpointProtocol.scala
- nsdb-rpc/src/main/protobuf/responseCommand.proto
This PR contains the code in charge to show correctly the tags information on the CLI.
> Added tags structures to rpc and cli modules

- nsdb-cluster/src/main/resources/cluster.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/CommitLogCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedSchemaCacheSpec.scala
- nsdb-cluster/src/test/resources/application.conf
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/CommitLogCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorSpec.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/CommitLogWriterActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/RollingCommitLogFileWriter.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializer.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/commit_log/StandardCommitLogSerializerSpec.scala
- nsdb-it/src/test/resources/minicluster.conf
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniClusterConf.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniClusterNode.scala
This PR is aimed to enhance CommitLog component to support a cluster aware write.
> Cluster-aware CommitLog 

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/SchemaCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeDoubleSummation.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeFacetDoubleSum.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeFacetLongSum.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeLongSummation.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeNode.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeSummation.java
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AllFacetIndexes.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/SchemaIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/lucene/Index.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/model/Schema.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/index/SchemaIndexTest.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
- project/Dependencies.scala
This PR adds support for sum aggregation in temporal queries.
e.g. 
`select sum(*) from metric group by interval 2d`
is now supported.
> Temporal sum

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeDoubleMinMax.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeFacetDoubleMinMax.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeFacetLongMinMax.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeFacetLongSum.java
- nsdb-core/src/main/java/org/apache/lucene/facet/range/LongRangeLongMinMax.java
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParserErrors.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
This PR adds support for min and max aggregation in temporal queries.
e.g.
```
select max(*) from metric group by interval 2d
select min(*) from metric group by interval 2d
```
are now supported.
> Temporal min max

- nsdb-cli/src/main/scala/io/radicalbit/nsdb/cli/table/ASCIITableBuilder.scala
This PR is for adding the metric info params in the CLI response
> [HOTFIX] Add metric info in describe metric response in CLI

- nsdb-cluster/src/main/resources/cluster.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDBAkkaCluster.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ClusterListener.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/DatabaseActorsGuardian.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
- nsdb-it/README.md
- nsdb-it/src/test/resources/minicluster.conf
- nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/PublishSubscribeClusterSpec.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/ReadCoordinatorClusterPassivationSpec.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/ReadCoordinatorClusterSpec.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/cluster/WriteCoordinatorClusterSpec.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/MiniClusterStarter.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NSDbMiniClusterNode.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/minicluster/NsdbMiniClusterConf.scala
- nsdb-it/src/test/scala/io/radicalbit/nsdb/test/MiniClusterSpec.scala
- nsdb-rpc/src/main/scala/io/radicalbit/nsdb/client/rpc/GRPCServer.scala
- project/Dependencies.scala
This PR introduces akka cluster bootstrap as a cluster formation mechanism.
Basically, it won't be necessary to specify seed nodes in order to start a cluster, but this will be formed using a discovery mechanism.
For more info see 
https://doc.akka.io/docs/akka-management/current/bootstrap/index.html
> Cluster bootstrap

- docs/RestApis.md
- version.sbt
This PR is for adding the missing documentation for an existing, but still not unveiled `get dbs` api.
This code has been already merged on master as part of a more comprehensive PR
> add doc for get dbs api

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NSDBAkkaCluster.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/NsdbCluster.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/CorsSupport.scala
- project/plugins.sbt
This PR moves the actor system initialization from a trait to its concrete implementation. 
This lazy initialization has the advantage of being more clear and facilitating an instrumentation (using kamon for instance)
> Lazy actorsystem implementation

- build.sbt
- nsdb-cluster/src/main/resources/application-common.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorAggregatedStatementsSpec.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
This PR aims to fix a little issue when a groupby ordered by value on a metric with value of type DECIMAL
> [BUGFIX] Fix ordering by value issue

- k8s/akka-cluster-stateful.yml
- k8s/nsdb-cluster-deployment.yml
- nsdb-cluster/src/main/resources/monitoring.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
This Pr aims to remove some redundant aggregations and limit operation that are performed twice in the read flow.
Besides, the docker container reference has been updated and the monitoring related env variables are added
> [HOTFIX] remove redundant aggregations 

- project/Dependencies.scala
This pr aims to update Kamon dependencies version in order to make them compatible with the lastest akka version
> [HOTFIX] update kamon version

- docs/SQL_doc.md
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorAggregatedStatementsSpec.scala
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/package.scala
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SqlStatementSerialization.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/TypeSupport.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/index/aux/FirstLastIndexSpec.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
- nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/ReadCoordinatorClusterSpec.scala
- nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
- nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLStatementSpec.scala
- project/Dependencies.scala
- project/build.properties
- project/dependencies.sbt
This PR introduces the first and last aggregations for group by queries.
e.g. 
`select first(*) from metric group by tag`
`select first(value) from metric group by tag`
> Introducing First and Last aggregation

- README.md
- build.sbt
- docker-compose.yml
- docs/Architecture.md
- docs/Clustering.md
- docs/JVM_API_doc.md
- docs/QuickStart.md
- docs/SQL_doc.md
- k8s/nsdb-cluster-deployment.yml
- k8s/nsdb-cluster-stateful.yml
- nsdb-cluster/src/main/resources/nsdb.conf
This PR aims to improve the existing documentation and to add a brief doc for the clustering part.
Also, minor improvements have been provided for the docker-compose and k8s example files
> Doc improvement

- nsdb-cluster/src/main/resources/nsdb.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/endpoint/GrpcEndpoint.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/STMultiNodeSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ClusterListenerTestActor.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/MetadataSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCacheSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedSchemaCacheSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/MultiNodeBaseSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/AbstractReadCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorErrorsSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedActors/LocalMetadataCoordinator.scala
- nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/ReadCoordinatorClusterSpec.scala
- nsdb-it/src/main/scala/io/radicalbit/nsdb/minicluster/NSDBAkkaMiniCluster.scala
- nsdb-it/src/main/scala/io/radicalbit/nsdb/minicluster/NsdbMiniCluster.scala
- nsdb-rpc/src/main/scala/io/radicalbit/nsdb/client/rpc/GRPCServer.scala
This PR aims to reinforce the fault tolerance, by preventing writes operation when the number of alive nodes is less than the replication factor.
More tests about fault tolerance will be added in a next PR
> High Availability Writes Reinforcement

- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/AbstractReadCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorAggregatedStatementsSpec.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AbstractStructuredIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/index/TimeSeriesIndexTest.scala
The aim of this PR is to remove redundant ordering (either lucene or post-processing ordering)
> Remove useless ordering, refactoring code

- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
- nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
- nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
The aim of this PR is to enhance both the SQL parser and the statement parser including average aggregation.
> Enhance sql parser and statement parser including avg aggregation

- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/package.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AllFacetIndexes.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetCountIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetRangeIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/FacetSumIndex.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/SumAndCountFacetCombiner.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/index/FacetIndexTest.scala
In this PR we combine the result of sum facet with count facet in a Bit. WE do this because we need these two values aggregated together for average aggregagation.
> Combine Sum and Count Facet Result into Bit

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/StatementParser.scala
- nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/TemporalReadCoordinatorSpec.scala
This PR concludes the temporal average implementation by providing post-processing.
> Temporal Average Postprocessing

- nsdb-cluster/src/main/resources/nsdb.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
- nsdb-cluster/src/test/resources/application.conf
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/configuration/NSDbConfig.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/PublisherActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/TemporaryIndex.scala
- project/Dependencies.scala
This PR aims at making tmp directory configurable.
Also, a temporary index is closed at the end of the publish operation and not garbage collected.
> [HOTFIX] make tmp directory configurable

- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/AbstractReadCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/AbstractTemporalReadCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorCharsetSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorTemporalAggregatedStatementsSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedData/MockedData.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/statement/ExpressionParser.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserSpec.scala
- nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
- nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLLikeExpressionSpec.scala
This PR fixes and reinforces the tests for equality and like expression with terms containing `?` and / or `!`
> [HOTFIX] Fix support for question and exclamation marks

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/AbstractClusterListener.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/AbstractReadCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorNegativeSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/mockedData/MockedData.scala
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/package.scala
- nsdb-core/src/main/java/org/apache/lucene/facet/taxonomy/DoubleTaxonomyFacets.java
- nsdb-core/src/main/scala/io/radicalbit/nsdb/index/AllFacetIndexes.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
- nsdb-sql/src/main/scala/io/radicalbit/nsdb/sql/parser/SQLStatementParser.scala
- nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/SelectSQLEqExpressionSpec.scala
This PR fixes a little bug that occurred in the facet collection process for an index that contains negative values.
Minor improvements on internal type system have been provided as well as a test suite that covers this scenario.
> [HOTFIX] Negative numbers management

- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinatorGlobalAggregatedStatementsSpec.scala
- nsdb-common/src/main/scala/io/radicalbit/nsdb/common/statement/SQLStatement.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/ShardReaderActor.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/post_proc/package.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/statement/StatementParserAggregationsSpec.scala
- nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/GlobalAggregationReadCoordinatorSpec.scala
- nsdb-sql/src/test/scala/io/radicalbit/nsdb/sql/parser/AggregationSQLStatementSpec.scala
Introducing global MAX(*) aggregation
> Make MAX(*) a global aggregation

- nsdb-cluster/src/main/resources/application-common.conf
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/ClusterSingletonWithSplitBrainResolutionSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/ClusterSingletonWithSplitBrainSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/DatabaseActorsGuardianForTest.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/SplitBrainFiveNodesResolutionSpec.scala
- nsdb-cluster/src/multi-jvm/scala/io/radicalbit/nsdb/split_brain/configs/SplitBrainSpecConfig.scala
- nsdb-scala-api/src/main/scala/io/radicalbit/nsdb/api/scala/example/NSDbStreamingMain.scala
- project/Dependencies.scala
This PR is for updating split brain plugin from lithium to the official one.
> Update Split Brain Plugin

- .gitignore
- build.sbt
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/ReplicatedMetadataCache.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/RetentionSpec.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/actors/MetricAccumulatorActor.scala
- nsdb-core/src/test/scala/io/radicalbit/nsdb/index/FacetIndexTest.scala
- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/QueryValidationApi.scala
- nsdb-it/src/it/scala/io/radicalbit/nsdb/cluster/TemporalReadCoordinatorSpec.scala
- nsdb-java-api/src/main/java/io/radicalbit/nsdb/api/java/NSDB.java
- nsdb-java-api/src/main/java/io/radicalbit/nsdb/api/java/example/NSDBStreaming.java
- nsdb-rpc/src/main/scala/io/radicalbit/nsdb/rpc/server/endpoint/GrpcEndpointServiceSQL.scala
- project/Commons.scala
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
This PR aims at adding a `subscribe` method to the java api in order to call the grpc subscribe endpoint, that so far was implemented only for the scala apis.
A dependency version and sbt update has been provided as well
> [HOTFIX] Add Java Subscribe Api

- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/AbstractClusterListener.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/actor/NodeActorsGuardian.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/ReadCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinator.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/extension/NSDbClusterSnapshot.scala
- nsdb-cluster/src/main/scala/io/radicalbit/nsdb/cluster/logic/LocalityReadNodesSelection.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/MetadataCoordinatorSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/RetentionSpec.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorBehaviour.scala
- nsdb-cluster/src/test/scala/io/radicalbit/nsdb/cluster/coordinator/WriteCoordinatorErrorsSpec.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/protocol/MessageProtocol.scala
- nsdb-core/src/main/scala/io/radicalbit/nsdb/util/FileUtils.scala
- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/ApiResources.scala
- nsdb-http/src/main/scala/io/radicalbit/nsdb/web/routes/CommandApi.scala
- nsdb-http/src/test/scala/io/radicalbit/nsdb/web/CommandApiSpec.scala
This is the cherry pick of  https://github.com/radicalbit/NSDb/pull/195
> [Cherry Pick] Cluster Topology and Get Locations Http Apis
